In [4]:
list = [1,2,3,4]

In [6]:
print("hello world")

hello world


In [8]:
import numpy as pd

In [9]:
np.zeros(3)

NameError: name 'np' is not defined

In [10]:
import numpy as np

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((3,))

array([0., 0., 0.])

In [13]:
a = np.zeros(3)
b = np.zeros((3,))
a == b

array([ True,  True,  True])

In [14]:
np.array_equal(a, b)

True

In [15]:
np.arrange(1,10,20)

AttributeError: module 'numpy' has no attribute 'arrange'

In [16]:
np.arange(1,10,20)

array([1])

In [17]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [18]:
np.random.randint(1,101, (3,3))

array([[17, 52,  8],
       [26, 38, 77],
       [87, 10,  1]])

In [19]:
np.zeros(3,4)

TypeError: Cannot interpret '4' as a data type

In [20]:
np.array([1,2,3])

array([1, 2, 3])

In [21]:
arr = np.random.randint(1, 11, 25)

In [22]:
arr

array([ 2, 10,  5,  6,  3,  9,  2, 10,  8,  9,  1,  4,  3,  9,  5,  7,  3,
        9,  6, 10,  4,  6,  7,  1,  2])

In [23]:
arr.reshape(5,5)

array([[ 2, 10,  5,  6,  3],
       [ 9,  2, 10,  8,  9],
       [ 1,  4,  3,  9,  5],
       [ 7,  3,  9,  6, 10],
       [ 4,  6,  7,  1,  2]])

In [24]:
arr = np.random.randint(1, 11, 25)
arr.shape

(25,)